# Generated by Django 4.0.3 on 2022-04-08 15:21

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='images/')),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePhoto', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='images/')),
                ('bio', models.TextField()),
                ('contacts', models.TextField()),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awwwards.post')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
