# Generated by Django 4.0.3 on 2022-04-12 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awwwards', '0003_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('design', models.PositiveSmallIntegerField(choices=[(1, '1-Poor'), (2, '2'), (3, '3'), (4, ''), (5, '5- Fair'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10-Good')], default=0)),
                ('usability', models.PositiveSmallIntegerField(choices=[(1, '1-Poor'), (2, '2'), (3, '3'), (4, ''), (5, '5- Fair'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10-Good')], default=0)),
                ('content', models.PositiveSmallIntegerField(choices=[(1, '1-Poor'), (2, '2'), (3, '3'), (4, ''), (5, '5- Fair'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10-Good')], default=0)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwwards.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
